name = "HaploSoup"
uuid = "7bf651b7-f892-4a16-8775-dfd0bc30e02c"
authors = ["Roland Laboulaye <rlaboulaye@gmail.com> and contributors"]
version = "0.1.0"

[deps]
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
VCFTools = "a620830f-fdd7-5ebc-8d26-3621ab35fbfe"

[compat]
NPZ = "0.4"
julia = "1.6"
